### ISSUE TITLE
Doesn't work as a web app

### ISSUE THREAD

**Issue by eprparadocs** [Mr-RobotDev/flutter-boilerplate#1]
I tried this and was hoping to see it working as a webapp. Couldn't get it to run. Same result as a Linux app.

**Comment by abdullahdevelops** [comment]
I just checked again. It's working perfectly fine. Of course, the UI is not according to web view. But the functionality is there.
- - - -
<img width="1440" alt="Screenshot 2023-03-06 at 2 06 26 PM" src="https://user-images.githubusercontent.com/44782056/223065165-659b6b8d-faac-45bd-834e-5b6c87c103f1.png">
